Fix and improve sample rate timing
CreaTe-M8-BME/Firmware pull request #6
Opened 2024-05-23 19:51 UTC by JonaMata

- Increased sample rate timer precision to allow for more specific sample rates
- Improved sample rate timing code to negate accumulating error

2024-05-24 07:06 UTC, FrankBosman requested changes
We should also first merge the blinking LED and merge it in this one so we don't have to flash them twice

2024-05-24 07:06 UTC, FrankBosman commented on esp32_bluetooth_host/esp32_bluetooth_host.ino
> +    Serial.println(frequency);
Maybe remove the debugging code, or make it more clear that it is to stay with a comment

2024-05-24 07:06 UTC, FrankBosman commented on esp32_bluetooth_host/esp32_bluetooth_host.ino
Update the version number

2024-05-24 12:30 UTC, JonaMata commented on esp32_bluetooth_host/esp32_bluetooth_host.ino
I'll do this when everything is merged and we're ready for deploying a new version

2024-05-24 17:49 UTC, FrankBosman requested changes
Could you update the version number and update the branch with main?

2024-05-27 08:56 UTC, MaxLiebe commented
Frank already mentioned my comments, LGTM otherwise

2024-05-27 12:01 UTC, FrankBosman approved these changes

2024-05-27 12:01 UTC, merged